spring:
  application:
    name: Pessoas WEB - DEVELOPMENT (H2)
  datasource:
    url: jdbc:h2:mem:pessoas
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.254:8180/realms/quarkus-keycloak-realm
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dll-auto: update
        format_sql: true
        show_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console